### PR TITLE
Bugfix: url to import project

### LINKED ISSUE #368: Import project: Support repository URLs with `.git` or `/` suffix
**Describe the bug**

When importing a project, the repository URL should support URLs with `.git` or `/` at the end.

<ins>This issue applies to both "Import new project" and "Create a project from a template" dialogs.</ins>

Currently:

* `.git` suffix is not accepted by the validation rule:
   <image src="https://github.com/ditrit/leto-modelizer/assets/20184007/7dac6a7c-71e5-47cd-9257-eb1d77910a40" width="300" />
   It should be accepted, because many users are used to copy/paste the URL from [GitHub's "Code" button](https://github.com/ditrit/leto-modelizer/assets/20184007/a10a324b-e15f-4ad0-8c56-c03a5d230835).

* `/` suffix is accepted by the validation rule, but the project name extracted from the URL is empty, and it causes an error 404 after importing the project.
   <image src="https://github.com/ditrit/leto-modelizer/assets/20184007/e4dbfad6-0125-4779-8a20-c667aa304d04" width="200" />
   The router redirected me to this URL: http://localhost:8080/projects//models.

**Application**

- `leto-modelizer` commit hash: `f59e63e9d861fb5d0f0849dc7983be3a76bd779a`.

### PR DESCRIPTION
**Pull request by Zorin95670**
Fix #368.

### CODE REVIEW

**Review by k-y0u — APPROVED** [review]

File: src/composables/QuasarFieldRule.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ export function notEmpty(t, value) {
  * the translated error message.
  */
 export function isGitRepositoryUrl(t, value) {
```
Comment (k-y0u) [inline src/composables/QuasarFieldRule.js:22]: isUrl

**Review by k-y0u — APPROVED** [review]

File: src/composables/QuasarFieldRule.js (hunk 1 above)
Comment (Zorin95670) [reply src/composables/QuasarFieldRule.js]: done
