### PR TITLE
Bugfix: nested object definition

### LINKED ISSUE #203: ObjectInput: Error with nested object attributes
**Describe the bug**

When I select a component with an object attribute nested inside another object attribute, the component details drawer is not shown. Here is the error in the console logs:

```
Uncaught (in promise) TypeError: Cannot read property 'find' of null
    at eval (ObjectInput.vue?b0af:103)
    at Proxy.forEach (<anonymous>)
    at Proxy.getSubAttributes (ObjectInput.vue?b0af:101)
    at eval (ObjectInput.vue?b0af:40)
    at renderFnWithContext (runtime-core.esm-bundler.js?f781:868)
    at hSlot (render.js?cdf5:4)
    at getTransitionChild (QExpansionItem.js?3b73:324)
    at eval (runtime-core.esm-bundler.js?f781:4234)
    at Proxy.renderFnWithContext (runtime-core.esm-bundler.js?f781:868)
    at Proxy.eval (runtime-core.esm-bundler.js?f781:1987)
```

Here is a sample component definition that can be used to reproduce this bug (in Terrator metadata):

```json
{
  "type": "myComponent",
  "model": "DefaultModel",
  "icon": "myIcon",
  "attributes": [
    {
      "name": "myObject",
      "type": "Object",
      "attributes": [
        {
          "name": "myNestedObject",
          "type": "Object",
          "attributes": [
            {
              "name": "myString",
              "type": "String"
            }
          ]
        }
      ]
    }
  ]
}

```

**Application (please complete the following information):**

- leto commit hash: `e2ecedf45dbc5bef50fd8b6c90a858075bfac740`

### PR DESCRIPTION
**Pull request by Zorin95670**
Resolved #203 .

### CODE REVIEW

File: src/components/inputs/ObjectInput.vue [hunk 1]
```diff
@@ -100,10 +100,11 @@ const hasError = computed(() => props.currentError !== null
  */
 function getSubAttributes(attribute) {
   const attributes = [];
+  const attributeValue = attribute.value || [];
 
   attribute.definition?.definedAttributes
     ?.forEach((definition) => {
-      const attr = attribute.value.find(({ name }) => name === definition.name);
+      const attr = attributeValue?.find(({ name }) => name === definition.name);
```
Comment (justinehell) [inline src/components/inputs/ObjectInput.vue:107]: I don't think you need the Optional Chaining

**Review by justinehell — CHANGES_REQUESTED** [review]
